web_scraping:
  LoginPage:
    username_input:
      ID: "user-name"
    password_input:
      ID: "password"
    login_button:
      ID: "login-button"

  ProductsPage:
    product_items:
      CLASS_NAME: "inventory_item"
    product_name:
      CLASS_NAME: "inventory_item_name"
    product_price:
      CLASS_NAME: "inventory_item_price"
